"""initial

Revision ID: 9e8c93be4290
Revises: 
Create Date: 2021-04-13 21:50:41.324963

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e8c93be4290'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('flash_cards',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('question', sa.String(length=1024), nullable=True),
    sa.Column('answer', sa.String(length=1024), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('flash_cards')
    # ### end Alembic commands ###
